name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Tell me about the feature
      placeholder: As a developer/user, I want...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Implementation scope:**
        - [ ] Implement...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Include any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm before submitting.
      options:
        - label: I have checked existing features and documentation to make sure this feature does not exist.
          required: true
