name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=18.15.x'

      - name: Install dependencies
        run: npm ci

      - name: Prettier fix
        run: npm run prettier:fix

      - name: Lint check
        run: npm run lint

      - name: Test build
        run: npm run build
        env:
          NODE_ENV: ${{ vars.ENV }}
          VITE_ROUTER_TYPE: ${{ vars.ROUTER_TYPE }}
          CI: true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ vars.BUILD_PATH }}
          name: ${{ vars.ARTIFACT_NAME }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: ${{ vars.ARTIFACT_NAME }}

      - name: Delete Artifacts
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.DELETE_ARTIFACTS_TOKEN }}
        run: |
          sudo apt-get install jq
          chmod +x .github/scripts/delete_artifacts.sh
          bash .github/scripts/delete_artifacts.sh
