name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18.15.x'

      - name: Install dependencies
        run: npm ci

      - name: Prettier fix
        run: npm run prettier:fix

      - name: Lint check
        run: npm run lint

      - name: Test build
        run: |
          export VITE_ROUTER_TYPE=hash
          npm run build
        env:
          CI: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages-build
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: gh-pages-build
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
